# Generated by Django 5.1.1 on 2024-09-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
