# Generated by Django 5.1.1 on 2024-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=255),
            preserve_default=False,
        ),
    ]
