# Generated by Django 5.1.1 on 2025-01-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('pos', 'POS'), ('transfer', 'Bank Transfer')], default='pos', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('requesting', 'Requesting'), ('paid', 'Paid'), ('failed', 'Failed')], default='requesting', max_length=20),
        ),
    ]
