# Generated by Django 5.1.1 on 2025-01-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='orders',
            field=models.ManyToManyField(related_name='payments', to='myapp.order'),
        ),
    ]
